- name: Install rclone and FUSE runtime packages
  dnf:
    name:
      - rclone
      - fuse3
    state: present

- name: Add read permission to other users
  file:
    path: /etc/fuse.conf
    state: file
    mode: "o=r"

- name: Allow non-root users to specify the allow_other or allow_root mount options
  lineinfile:
    dest: /etc/fuse.conf
    regexp: "^#\\s*user_allow_other$"
    line: "user_allow_other"
    state: present
    backrefs: yes

- name: Write rclone config
  template:
    src: rclone.conf.j2
    dest: "{{ s3_mount_rclone_config_path }}"
    owner: root
    mode: "0644"
