- name: Check if architecture is supported
  fail:
    msg: "You cannot install RabbitMQ on this architecture. Supported architectures: x86_64, aarch64."
  when: ansible_architecture not in ['x86_64', 'aarch64']

- name: Install rabbitmq repo
  template:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo
    mode: "0644"

- name: Install RabbitMQ Erlang RPM for aarch64
  when: ansible_architecture == 'aarch64'
  block:
    - name: Import RabbitMQ release signing key for direct ARM Erlang RPM install
      rpm_key:
        state: present
        key: https://github.com/rabbitmq/signing-keys/releases/download/3.0/rabbitmq-release-signing-key.asc

    - name: Install RabbitMQ Erlang RPM for aarch64
      dnf:
        allow_downgrade: no
        name: "{{ rabbitmq_erlang_aarch64_rpm_url }}"
        state: present
