- name: Ensure AWS backup vault exists
  amazon.aws.backup_vault:
    state: present
    backup_vault_name: "{{ aws_backup_vault_name }}"
    region: "{{ aws_region }}"
  when: aws_backup_enabled | bool
  delegate_to: localhost
  become: no

- name: Ensure AWS backup plan exists
  amazon.aws.backup_plan:
    state: present
    backup_plan_name: "{{ aws_backup_plan_name }}"
    region: "{{ aws_region }}"
    tags: "{{ aws_tags_default }}"
    rules:
      - rule_name: "{{ aws_backup_plan_name }}"
        target_backup_vault_name: "{{ aws_backup_vault_name }}"
        schedule_expression: "{{ aws_backup_schedule_expression }}"
        start_window_minutes: "{{ aws_backup_start_window_minutes }}"
        completion_window_minutes: "{{ aws_backup_completion_window_minutes }}"
        lifecycle:
          delete_after_days: "{{ aws_backup_delete_after_days }}"
        recovery_point_tags: "{{ aws_backup_recovery_point_tags }}"
  when: aws_backup_enabled | bool
  delegate_to: localhost
  become: no

- name: Gather existing AWS backup selections
  amazon.aws.backup_selection_info:
    backup_plan_name: "{{ aws_backup_plan_name }}"
    region: "{{ aws_region }}"
  when: aws_backup_enabled | bool
  register: aws_backup_existing_selections_info
  delegate_to: localhost
  become: no

- name: Ensure stale AWS backup selections are absent
  amazon.aws.backup_selection:
    state: absent
    backup_plan_name: "{{ aws_backup_plan_name }}"
    selection_name: "{{ item.selection_name }}"
    region: "{{ aws_region }}"
  when:
    - aws_backup_enabled | bool
    - item.selection_name not in aws_backup_selections.keys()
  loop: "{{ aws_backup_existing_selections_info.backup_selections | default([]) }}"
  loop_control:
    label: "{{ item.selection_name }}"
  delegate_to: localhost
  become: no

- name: Ensure AWS backup tag selections exist
  amazon.aws.backup_selection:
    state: present
    backup_plan_name: "{{ aws_backup_plan_name }}"
    selection_name: "{{ item.key }}"
    iam_role_arn: "arn:aws:iam::{{ aws_account_id }}:role/service-role/AWSBackupDefaultServiceRole"
    region: "{{ aws_region }}"
    resources:
      - "*"
    conditions:
      string_equals: >-
        {{
          item.value
          | combine(aws_tags_default)
          | prefix_keys('aws:ResourceTag/')
          | dict2items(key_name='condition_key', value_name='condition_value')
        }}
  when: aws_backup_enabled | bool
  loop: "{{ aws_backup_selections | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  delegate_to: localhost
  become: no

- name: Ensure AWS backup plan is absent
  amazon.aws.backup_plan:
    state: absent
    backup_plan_name: "{{ aws_backup_plan_name }}"
    region: "{{ aws_region }}"
  when: not aws_backup_enabled | bool
  delegate_to: localhost
  become: no
