- name: Validate SSH tunnel private key secret
  assert:
    that:
      - (ssh_tunel_private_key_secret | default('', true) | string | length) > 0
    fail_msg: "ssh_tunel_private_key_secret must be set when mageops_ssh_proxy_persistant is enabled."
    quiet: true

- name: Generate public key
  command:
    cmd: ssh-keygen -y -f /dev/stdin
    stdin: "{{ ssh_tunel_private_key_secret | b64decode }}"
  register: _ssh_tunel_public_key
  delegate_to: localhost
  become: no
  no_log: true

- name: Create tunel user
  user:
    name: tunel
    state: present
    shell: /sbin/nologin

- name: Install key
  authorized_key:
    user: tunel
    state: present
    exclusive: yes
    key: "{{ _ssh_tunel_public_key.stdout }}"
